In [49]:
import numpy as np
from scipy.optimize import linprog
from basic_utils import nn2na, get_usage_string, get_min_cut

# Node-Node matrix
NN = np.array([[0, 1, 1, 0, 0, 0],
               [0, 0, 0, 1, 0, 1],
               [0, 0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 1],
               [1, 0, 0, 0, 0, 0]])



# A matrix, which is Node-arc matrix. Arcs is a tuple with dim(arcs) = #arcs in the graph
A, arcs = nn2na(NN)
# Cost matrix. Since we have no costs for this type of problem, we assign zero for each arc, and -1 for (t - s) arc to force its use
# Dim(C) = #Arcs
C = np.zeros(len(arcs))
C[len(arcs)-1] = -1
# b is always zero since there is not flow that keeps on any node.
# Dim(b) = #nodes
b = np.array([0, 0, 0, 0, 0, 0])
# Upper and lower bound. For t-s arc, there is no capacity limit.
u = np.array([7, 1, 2, 3, 2, 1, 2, None])
bounds = tuple([(0, u[arc]) for arc in range(0, A.shape[1])])

print("Input arguments: \n",
"- A matrix:\n", A,
"\n- Cost matrix: \n", C,
"\n- b vector: \n", b,
"\n- Bounds: \n", bounds
)

# OPTIMIZE:
result = linprog(C, A_eq=A, b_eq=b, bounds=bounds, method='simplex')

def get_min_cut(arc_idxs, np_res_flow, np_capacity):
    np_capacity = np.where(np_capacity == None, 999, np_capacity)
    idxs = np.argwhere((np_res_flow - np_capacity) == 0)
    return [arc_idxs[i[0]] for i in idxs]

print("\nArcs usage:")
for i in range(len(arcs)):
        print("Arc", arcs[i], "->", result.x[i].astype(int), "/", u[i])

print("\nMaximum flow F:", result.x[-1].astype(int))

print("\nMin cut", get_min_cut(arcs, res.x, np.array(u)))


Input arguments: 
 - A matrix:
 [[ 1  1  0  0  0  0  0 -1]
 [-1  0  1  1  0  0  0  0]
 [ 0 -1  0  0  1  0  0  0]
 [ 0  0 -1  0  0  1  0  0]
 [ 0  0  0  0 -1  0  1  0]
 [ 0  0  0 -1  0 -1 -1  1]] 
- Cost matrix: 
 [ 0.  0.  0.  0.  0.  0.  0. -1.] 
- b vector: 
 [0 0 0 0 0 0] 
- Bounds: 
 ((0, 7), (0, 1), (0, 2), (0, 3), (0, 2), (0, 1), (0, 2), (0, None))

Arcs usage:
Arc (0, 1) -> 4 / 7
Arc (0, 2) -> 1 / 1
Arc (1, 3) -> 1 / 2
Arc (1, 5) -> 3 / 3
Arc (2, 4) -> 1 / 2
Arc (3, 5) -> 1 / 1
Arc (4, 5) -> 1 / 2
Arc (5, 0) -> 5 / None

Maximum flow F: 5

Min cut [(0, 2), (1, 5), (3, 5)]
