In [140]:
import numpy as np
from scipy.optimize import linprog
from basic_utils import nn2na
from operator import itemgetter

# Node-Node matrix
NN = np.array([[0, 0, 0, 1, 1],
               [0, 0, 0, 1, 1],
               [0, 0, 0, 1, 1],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

# A matrix, which is Node-arc matrix. Arcs is a tuple with dim(arcs) = #arcs in the graph
A, arcs = nn2na(NN)

# Cost matrix. Dim(C) = #Arcs
C = np.array([10, 20, 10, 10, 10, 30])

# b Matrix. Dim(b) = #nodes
b = np.array([10, 20, 15, -25, -20])

# Upper and lower bound.
bounds = tuple([(0, None) for arc in range(0, A.shape[1])])

print("Input arguments:\n\n",
"- A matrix:\n", A,
"\n- Cost matrix: \n", C,
"\n- b vector: \n", b,
"\n- Bounds: \n", bounds
)
   
# OPTIMIZE:
result = linprog(C, A_eq=A, b_eq=b, bounds=bounds, method='simplex')

print("\nResults:")
print("\nQuantities sent through each arc: ")
for i in range(len(result.x)):
    print(arcs[i], "->", result.x[i].astype(int))
print("\nTotal Cost: ", result.fun)

Input arguments:

 - A matrix:
 [[ 1  1  0  0  0  0]
 [ 0  0  1  1  0  0]
 [ 0  0  0  0  1  1]
 [-1  0 -1  0 -1  0]
 [ 0 -1  0 -1  0 -1]] 
- Cost matrix: 
 [10 20 10 10 10 30] 
- b vector: 
 [ 10  20  15 -25 -20] 
- Bounds: 
 ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None))

Results:

Quantities sent through each arc: 
(0, 3) -> 10
(0, 4) -> 0
(1, 3) -> 0
(1, 4) -> 20
(2, 3) -> 15
(2, 4) -> 0

Total Cost:  450.0
